version: "1.0"
info:
  model: int-scaffold
services:
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.0.0.0.433
- serviceName: edge.testp1.integrations:test2
  packages:
  - name: EdgeTestp1
    version: "1.0"
packages:
- name: EdgeTestp1
  gitServerName: ICAccount0731
  gitUrl: https://github.com/MeghaRaj69/EdgeTestp1
  gitUsername: MeghaRaj69
  gitToken: edge.scaffolding.EdgeTestp1.ICAccount0731.gitToken
  gitBranch: testp1
